### ISSUE TITLE
More professional downloading, GUI, and translation

### ISSUE THREAD

**Issue by its-mrarsikk** [MatusGuy/youtube-dl_GUI#2]
# More professional downloading
I want to make downloading more professional and translate the application. Those are things that i suggest to enhance downloading:
* Setting speed of output *(like 1x, 2x)*
* Setting quality of output *(like 1080p, 140p)*
* Selecting subtitle language if turned on *(like Russian, Espanol)*
* Other settings *(like bitrate)*
# Enhance GUI
First, split the Destination field to 3 separate fields:
* Destination folder *(like D:/ydl/dest)*
* File name (without file type) *(like My favourite audio album 2007)*
* File type *(like MP4, MOV)*

I know that this is a minor change, but to make the estimated time field more eye-friendly, replace **ETA** with **Estimated time left**.
# Translation
It'd be better if the app was translated to some languages as **Russian**, **Espanol** and etc. And, luckily, i can help you with it! Because my nationality is russian, thus my native lang is Russian, i can fully translate your app to Russian! *except coding the localization*
# Easter egg
How can we live without easter eggs! I can suggest one.
When you click the `i` button in the corner and click the logo 10 times, background of info window turns black, and the logo turn orange-white.
*sorry for that*

**Comment by MatusGuy** [comment]
> More professional downloading

Usually, features that improve downloading come from youtube-dl itself.
Here, I will list which features you asked for are available and are usable in youtube-dl GUI.

- [ ] Output playback speed
  - This actually possible, but it's so confusing that I might aswell mark it as unavailable.
  FFmpeg can do this using two commands, one for changing the video speed and another for the audio speed.
  See the following:
  https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video
  If you know how to use batch files, then for now, make a batch file named `changePlaybackSpeed.bat` with the following content:
    ```bat
     echo "usage: changePlaybackSpeed [file] [speed]"
     rem speed will actually multiply the video and audio playback speed by the value that was sent
     rem for example, 0.5 will double the playback speed
     rem atempo filter can only speed up from 0.5 to 2.0
     
     ffmpeg -i %1 -filter:v "setpts=%2*PTS" %1
     ffmpeg -i %1 -filter:a "atempo=%2" -vn %1
     ```
     Then, go to Preferences > Additional switches and add `--exec changePlaybackSpeed.bat [filename][output template].[extension] [speed]`
     Change the parameters surrounded by square brackets to your settings
     If it doesn't work, try installing FFmpeg in your computer.

- [x] Output quality
   - This is already possible, via Preferences > Additional switches.
      First, go there and add `-F` and click download to list all available qualities
      Go to View > Console Output
      There will appear some numbers with information next to them
      Look for the quality you want and copy that number
      Go back to Preferences > Additional switches.
      Delete `-F`, put `-f q` and switch q with the number you copied.
      If it downloads video only, then look closer, as there's gotta be something saying "video-only" in that list of qualities
      ### But…!
      I'm planning to add GUI support for this in a later version, stay tuned.

- [x] Embed subtitles with other languages
   - Again, possible via additional switches but planned on adding GUI support
   Add these three additional switches: `--sub-lang [lang] --convert-subs srt --write-sub`
   Switch lang to the language you want, in your case, `ru`, I guess. Hopefully it works

- [x] Bit-rate
   - Isn't this similar to output quality?

> Enhance GUI

Goodie, my favourite part.

> First, split the Destination field to 3 separate fields

What!?
What's so wrong about the current destination group box?
Actually, I thought about it and your suggestion makes sense, but I don't think it's in the way you intended it to be.

>- File name (without file type) *(like My favourite audio album 2007)*

You see Configuration > Output Template? I never liked that thing, someone told me to add it and I was new to making applications.
This'd be a great chance to remove it. But then the configuration menu would become a little… alone…
Don't worry. I'm adding a settings page later.

>- File type *(like MP4, MOV)*

This one makes sense because of the output quality GUI support, quality depends on file format. And this would help distinguish what the user wants.

> Translation

I've been planning on adding translation for a while now…

> And, luckily, i can help you with it! Because my nationality is russian, thus my native lang is Russian, i can fully translate your app to Russian!

That's a cool offer from you!

> *except coding the localization*

I don't think you need to do that, we'll see

> Easter egg

Yeah, I might add an easter egg later, but not the one you suggested because you just told it in public.

Don't worry, I won't ban the app to russian people, I have russian friends and I feel them when they say Roivo banned Angry Birds in their country.

### Any questions or notes?

**Comment by Purpley1** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by its-mrarsikk** [comment]
@MatusGuy, how can i translate it, if you agree?
I'd like a `txt` document with english titles, and near i write the russian translation. If it doesn't seems good to you, say me!

**Comment by MatusGuy** [comment]
> I'd like a `txt` document with english titles

You can use `ts` files (Qt translation files, not Typescript) and their associated program, Qt Linguist.

>Yea, i do. But i can't understand what is that thing, and what to fill it 😑 How is it related to file name? Ok.

It adds info to the file name.
This is only useful to very specific cases where you need to download a bunch of files and they all have `%(playlist_index)s - %(title)s`at the end of the filename.

> I think, not many people can understand that:
X:/Y/Z/.abc, like, it can be understood as "File without name", what we don't need. It'd be really better, if you just split it into: folder, type, name. That'd be really better and understandable.

Kind of why I wanted to remove output template.

**Comment by its-mrarsikk** [comment]
> You can use ts files (Qt translation files, not Typescript) and their associated program, Qt Linguist.
oh good,i'll look into it later

**Comment by its-mrarsikk** [comment]
# I can't understand how to use TS files and Qt Linguist
I readen some documentation, but didn't understand everything at all. Can you please send me instructions and `ts` files that i need to fill? If you do, i'll heavily appreciate it.
# I don't need anything in return
I will just love to contribute higher than open an issue, because it's my first ever time i am doing this! I don't want anything in return, why should i? Programming and dev is just my hobby now, and i don't need any pay while it's my hobby!
# Where to get Qt Linguist
Almost forgot, where can i get Qt Linguist? Please, send me the download link, i'll appreciate it.

**Comment by MatusGuy** [comment]
Yeah, generating the `ts` file is a job of mine, in a later update I may teach you how to use Qt Linguist.

**Comment by its-mrarsikk** [comment]
Why did you close it? I don't think we're done.

**Comment by MatusGuy** [comment]
I want to continue this thread in discord
Also, here's a download to Qt Designer (which also comes with Qt Linguist):
https://build-system.fman.io/static/public/files/Qt%20Designer%20Setup.exe

**Comment by its-mrarsikk** [comment]
OK
